main: net.lotrcraft.minepermit.MinePermit
author: Numenorean95
authors: [tcoan98]
name: MinePermit
version: 2.0.1

commands:
    plot:
        description: Deals with buying and managing plots.
        usage: |
            /<command> list [world]
            /<command> price <x>:<z> <x>:<z>
            /<command> buy <x>:<z> <x>:<z> [name]
            /<command> <plot_name>
        permission: mp.plot
    minepermit:
        description: Core minepermit commands
        aliases: mp
        usage: |
            /<command> init <world>
        permission: mp.core
