main: net.lotrcraft.minepermit.MinePermit
author: Numenorean95
authors: tcoan98
name: MapLoader
version: 2.0.0

commands:
    plot:
        description: Deals with buying and managing plots.
        usage: |
            /<command> list [world]
            /<command> price <x>:<z> <x>:<z>
            /<command> buy <x>:<z> <x>:<z> [name]
            /<command> <plot_name>
        permission: mp.plot
